import { LlamaSettings, VpsSpecs } from './types.js';

export class LlamaConfigGenerator {
  static generateServerScript(settings: LlamaSettings, specs: VpsSpecs, modelFilePath: string): string {
    const flags: string[] = [
      `llama-server`,
      `-m '${modelFilePath}'`,
      `--host 0.0.0.0`,
      `--port 8080`,
      `-t ${settings.threads || specs.cpuCores || 4}`,
      `-np 1`,
      `-c ${settings.contextSize || 32768}`,
      `-b ${settings.batchSize || 512}`,
      `-ub ${settings.batchSize || 512}`
    ];

    if (settings.enableFlashAttn) {
      flags.push(`-fa on`);
    }

    if (settings.kvCacheQuant) {
      flags.push(`--cache-type-k ${settings.kvCacheQuant}`);
      flags.push(`--cache-type-v ${settings.kvCacheQuant}`);
      flags.push(`--kv-unified`);
    }

    flags.push(`--cache-reuse 256`);

    if (settings.enableMtp) {
      flags.push(`--spec-type draft-mtp`);
      flags.push(`--spec-draft-n-max 2`);
    }

    if (settings.isMoe) {
      // MoE specific tuning: optimize batch size & memory
      flags.push(`--jinja`);
    } else {
      flags.push(`--jinja`);
    }

    flags.push(`--chat-template-kwargs '{"preserve_thinking": true}'`);
    flags.push(`--timeout 0`);
    flags.push(`--metrics`);

    const commandStr = flags.join(' \\\n    ');

    return `#!/bin/bash
# Auto-generated by OpenClaw Daytona Control Panel
MODEL="${modelFilePath}"

if tmux has-session -t llama 2>/dev/null; then
  echo "[OK] llama-server is already active. Attach via: tmux attach -t llama"
else
  echo "[*] Starting llama-server (${settings.contextSize} context, MTP: ${settings.enableMtp}, Flash-Attn: ${settings.enableFlashAttn})..."
  tmux new-session -d -s llama "${commandStr} 2>&1 | tee /home/daytona/llama-server.log"
  echo "[OK] llama-server daemon started in background tmux session 'llama'."
fi
`;
  }

  static generateDownloadScript(downloadUrl: string, modelDir = '/home/daytona/models', filename = 'model.gguf', expectedBytes?: number): string {
    const byteCheck = expectedBytes && expectedBytes > 0
      ? `
ACTUAL_BYTES=$(stat -c %s "\${MODEL_PATH}" 2>/dev/null || echo 0)
if [ "$ACTUAL_BYTES" -ne "${expectedBytes}" ]; then
  echo "[ERROR] Size mismatch! Expected ${expectedBytes}, got $ACTUAL_BYTES"
  exit 1
fi
echo "[OK] Verified exact model weights integrity (\${ACTUAL_BYTES} bytes)."
`
      : 'echo "[OK] Download completed."';

    return `#!/usr/bin/env bash
set -euo pipefail

MODEL_DIR="${modelDir}"
MODEL_FILENAME="${filename}"
MODEL_PATH="\${MODEL_DIR}/\${MODEL_FILENAME}"

mkdir -p "\${MODEL_DIR}"

echo "[*] Downloading model via multi-stream aria2c..."
if ! command -v aria2c >/dev/null 2>&1; then
  sudo apt-get update -qq && sudo apt-get install -y -qq aria2
fi

aria2c -x 8 -s 8 -k 1M --summary-interval=5 -d "\${MODEL_DIR}" -o "\${MODEL_FILENAME}" "${downloadUrl}"
${byteCheck}
`;
  }

  static getAdaptedConfigForRetry(current: LlamaSettings, attempt: number): LlamaSettings {
    const adapted = { ...current };

    if (attempt === 1) {
      // Step down context size to reduce KV memory pressure
      adapted.contextSize = Math.max(8192, Math.floor(current.contextSize / 2));
      adapted.kvCacheQuant = 'q4_0';
    } else if (attempt === 2) {
      // Step down batch size and context
      adapted.contextSize = 8192;
      adapted.batchSize = 256;
      adapted.kvCacheQuant = 'q4_0';
    } else if (attempt >= 3) {
      // Emergency low-footprint mode: disable MTP, 4k context, 128 batch
      adapted.contextSize = 4096;
      adapted.batchSize = 128;
      adapted.enableMtp = false;
      adapted.kvCacheQuant = 'q4_0';
    }

    return adapted;
  }
}
